baseURL = 'https:www.faroukfaiz.com'
languageCode = 'en-us'
title = 'Portfolio'
theme = "hugo-resume"


[params]
address = "Paris, France"
email = "faiz@eurecom.fr"
favicon = "/favicon.ico"
firstName = "Farouk"
lastName = "Faiz"
profileImage = "profile.jpg"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showSkills = true
publishDir = "docs"

[[params.handles]]
link = "https://www.linkedin.com/in/faizfarouk/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/faroukfaiz10/"
name = "GitHub"